version: 2.1

description: |
  Create a Formula for Homebrew
  https://github.com/izumin5210/orbs-for-tools

#  Common
#----------------------------------------------------------------
common:
  release-params: &release-params
    tap:
      type: string
      default: $HOMEBREW_TAP_REPO_SLUG
      description: "GitHub repository slug(<username>/<repository>) for Homebrew Tap"
    token:
      type: string
      default: $GITHUB_TOKEN
      description: "GitHub access token to create/update formulae on homebrew tap repository"
    commit-message:
      type: string
      default: "Bump ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} formula"
      description: "A message for commiting Homebrew formulae"
    committer-name:
      type: string
      default: $GITHUB_USER
      description: "A github username for commiting Homebrew formulae"
    committer-email:
      type: string
      default: $GITHUB_EMAIL
      description: "An email for commiting Homebrew formulae"
    formula:
      type: string
      default: "Formula/${CIRCLE_PROJECT_REPONAME}.rb"
      description: "Path to formula file"
    maltmill-version:
      type: string
      default: v0.4.1
      description: "Version of github.com/Songmu/maltmill"

#  Executors
#----------------------------------------------------------------
executors:
  default:
    docker:
      - image: circleci/buildpack-deps:latest

#  Commands
#----------------------------------------------------------------
commands:
  update:
    description: Create a new Formula for Homebrew
    parameters:
      <<: *release-params

    steps:
      - run:
          name: "[homebrew] Validate envs"
          command: |
            if [ -z "<<parameters.committer-name>>" ]; then
              echo "GITHUB_USER must be set"
              exit 1
            fi

            if [ -z "<<parameters.committer-email>>" ]; then
              echo "GITHUB_EMAIL must be set"
              exit 1
            fi

            if [ -z "<<parameters.token>>" ]; then
              echo "GITHUB_TOKEN must be set"
              exit 1
            fi

            if [ -z "<<parameters.tap>>" ]; then
              echo "HOMEBREW_TAP_REPO_SLUG or `tap` param must be set"
              exit 1
            fi

      - run:
          name: "[homebrew] Install tools"
          command: |
            archive=maltmill_<<parameters.maltmill-version>>_linux_amd64
            curl -L https://github.com/Songmu/maltmill/releases/download/<<parameters.maltmill-version>>/${archive}.tar.gz | tar xzf -
            sudo cp ./${archive}/maltmill /usr/local/bin/
            rm -rf ./${archive}

      - run:
          name: "[homewbrew] Create or update Formula"
          command: |
            curl \
              -o content.json \
              -H "Authorization: token <<parameters.token>>" \
              https://api.github.com/repos/<<parameters.tap>>/contents/<<parameters.formula>>

            if [ "$(jq -M .content content.json)" = 'null' ]; then
              maltmill new -token <<parameters.token>> -w $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
              content=$(base64 -i -w 0 $CIRCLE_PROJECT_REPONAME.rb)
              curl \
                --fail \
                -X PUT \
                -H "Authorization: token <<parameters.token>>" \
                -d "{ \"message\": \"<<parameters.commit-message>>\", \"content\": \"$content\", \"committer\": { \"name\": \"<<parameters.committer-name>>\", \"email\": \"<<parameters.committer-email>>\" } }" \
                https://api.github.com/repos/<<parameters.tap>>/contents/<<parameters.formula>>
            else
              jq -M -r .content content.json | base64 -d > $CIRCLE_PROJECT_REPONAME.rb
              maltmill -token <<parameters.token>> -w $CIRCLE_PROJECT_REPONAME.rb
              content=$(base64 -i -w 0 $CIRCLE_PROJECT_REPONAME.rb)
              sha=$(jq -M -r .sha content.json)
              curl \
                --fail \
                -X PUT \
                -H "Authorization: token <<parameters.token>>" \
                -d "{ \"message\": \"<<parameters.commit-message>>\", \"content\": \"$content\", \"sha\": \"$sha\", \"committer\": { \"name\": \"<<parameters.committer-name>>\", \"email\": \"<<parameters.committer-email>>\" } }" \
                https://api.github.com/repos/<<parameters.tap>>/contents/<<parameters.formula>>
            fi

#  Jobs
#----------------------------------------------------------------
jobs:
  update:
    description: Create a new Formula for Homebrew

    executor: <<parameters.executor>>

    parameters:
      <<: *release-params
      executor:
        description: Executor to use for building applications
        type: executor
        default: default

    steps:
      - update:
          tap: <<parameters.tap>>
          token: <<parameters.token>>
          committer-name: <<parameters.committer-name>>
          committer-email: <<parameters.committer-email>>
          commit-message: <<parameters.commit-message>>
          formula: <<parameters.formula>>
          maltmill-version: <<parameters.maltmill-version>>
