version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.8.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          name: pack-go-crossbuild
          source-dir: src/go-crossbuild
          destination-orb-path: packed/go-crossbuild/orb.yml
          workspace-path: packed/go-crossbuild/orb.yml
          artifact-path: packed/go-crossbuild/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-go-crossbuild
          context: orb-publishing
          orb-name: izumin5210/go-crossbuild
          orb-path: workspace/packed/go-crossbuild/orb.yml
          requires:
            - pack-go-crossbuild

      - orb-tools/pack:
          name: pack-github-release
          source-dir: src/github-release
          destination-orb-path: packed/github-release/orb.yml
          workspace-path: packed/github-release/orb.yml
          artifact-path: packed/github-release/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-github-release
          context: orb-publishing
          orb-name: izumin5210/github-release
          orb-path: workspace/packed/github-release/orb.yml
          requires:
            - pack-github-release

      - orb-tools/pack:
          name: pack-homebrew
          source-dir: src/homebrew
          destination-orb-path: packed/homebrew/orb.yml
          workspace-path: packed/homebrew/orb.yml
          artifact-path: packed/homebrew/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-homebrew
          context: orb-publishing
          orb-name: izumin5210/homebrew
          orb-path: workspace/packed/homebrew/orb.yml
          requires:
            - pack-homebrew

      - orb-tools/pack:
          name: pack-protobuf
          source-dir: src/protobuf
          destination-orb-path: packed/protobuf/orb.yml
          workspace-path: packed/protobuf/orb.yml
          artifact-path: packed/protobuf/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-protobuf
          context: orb-publishing
          orb-name: izumin5210/protobuf
          orb-path: workspace/packed/protobuf/orb.yml
          requires:
            - pack-protobuf

      - orb-tools/pack:
          name: pack-inline
          source-dir: src/inline
          destination-orb-path: packed/inline/orb.yml
          workspace-path: packed/inline/orb.yml
          artifact-path: packed/inline/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-inline
          context: orb-publishing
          orb-name: izumin5210/inline
          orb-path: workspace/packed/inline/orb.yml
          requires:
            - pack-inline
