version: 2.1

description: |
  Build Go applications for multiplatform
  https://github.com/izumin5210/orbs-for-tools

#  Common
#----------------------------------------------------------------
common:
  gox-params: &goxz-params
    app_name:
      type: string
      default: $CIRCLE_PROJECT_REPONAME
    arch:
      type: string
      default: "amd64"
      description: "Space or comma separated list of GOARCH"
    dest:
      type: string
      default: "./artifacts"
      description: "Path to destination directory of built binaries"
    ldflags:
      type: string
      default: "'-ldflags' to pass to go build"
    tags:
      type: string
      default: "'-tags' to pass to go build"
    os:
      type: string
      default: "darwin,linux,windows"
      description: "Space or comma separated list of GOOS"

#  Executors
#----------------------------------------------------------------
executors:
  default:
    parameters:
      tag:
        description: Specify circleci/golang image tag
        type: string
        default: 'latest'
    docker:
      - image: circleci/golang:<< parameters.tag >>

#  Commands
#----------------------------------------------------------------
commands:
  build:
    description: Build an application
    parameters:
      <<: *goxz-params
      packages:
        type: string

    steps:
      - run:
          name: "[go-crossbuild] Install tools"
          command: go get github.com/Songmu/goxz/cmd/goxz

      - run:
          name: "[go-crossbuild] Build an application"
          command: |
            goxz \
              -arch="<<parameters.arch>>" \
              -build-ldflags="<<parameters.ldflags>>" \
              -build-tags="<<parameters.tags>>" \
              -d="<<parameters.dest>>" \
              -n="<<parameters.app_name>>" \
              -os="<<parameters.os>>" \
              <<parameters.packages>>

#  Jobs
#----------------------------------------------------------------
jobs:
  build:
    executor: <<parameters.executor>>
    description: Build an application for multiplatform

    parameters:
      <<: *goxz-params
      executor:
        description: Executor to use for building applications
        type: executor
        default: default
      workspace-root:
        type: string
        default: "."
      attach-workspace:
        type: boolean
        default: true
      persist-to-workspace:
        type: boolean
        default: true
      persist-paths:
        type: string
        default: "."
      # for build job
      packages:
        type: string

    steps:
      - when:
          condition: <<parameters.attach-workspace>>
          steps:
            - attach_workspace:
                at: <<parameters.workspace-root>>
      - build:
          packages: <<parameters.packages>>
          # gox-params
          app_name: <<parameters.app_name>>
          arch: <<parameters.arch>>
          dest: <<parameters.dest>>
          ldflags: <<parameters.ldflags>>
          tags: <<parameters.tags>>
          os: <<parameters.os>>
      - when:
          condition: <<parameters.persist-to-workspace>>
          steps:
            - persist_to_workspace:
                root: <<parameters.workspace-root>>
                paths:
                  - <<parameters.persist-paths>>
